# Słownik mapujący typy Google Places API na polskie nazwy.
# Wartość None oznacza, że dany typ nie powinien być wyświetlany użytkownikowi jako główna kategoria.

PLACE_TYPES_PL = {
    # --- Kultura i Sztuka ---
    "art_gallery": "Galeria sztuki",
    "art_studio": "Pracownia artystyczna",
    "auditorium": "Audytorium",
    "cultural_landmark": "Zabytek kultury",
    "historical_place": "Miejsce historyczne",
    "historical_landmark": "Zabytek historyczny",
    "monument": "Pomnik",
    "museum": "Muzeum",
    "performing_arts_theater": "Teatr",
    "sculpture": "Rzeźba",
    "library": "Biblioteka",
    "cultural_center": "Centrum kultury",
    "opera_house": "Opera",
    "philharmonic_hall": "Filharmonia",
    "planetarium": "Planetarium",

    # --- Rozrywka i Rekreacja ---
    "amusement_center": "Centrum rozrywki",
    "amusement_park": "Park rozrywki",
    "aquarium": "Oceanarium",
    "bowling_alley": "Kręgielnia",
    "casino": "Kasyno",
    "comedy_club": "Klub komediowy",
    "concert_hall": "Sala koncertowa",
    "movie_theater": "Kino",
    "night_club": "Klub nocny",
    "park": "Park",
    "dog_park": "Wybieg dla psów",
    "video_arcade": "Salon gier",
    "zoo": "Ogród zoologiczny",
    "water_park": "Park wodny",
    "tourist_attraction": "Atrakcja turystyczna",
    "observation_deck": "Taras widokowy",
    "ferris_wheel": "Diabelski młyn",
    "roller_coaster": "Kolejka górska",
    "marina": "Przystań",
    "botanical_garden": "Ogród botaniczny",
    "national_park": "Park Narodowy",

    # --- Jedzenie i Picie ---
    "restaurant": "Restauracja",
    "bar": "Bar",
    "cafe": "Kawiarnia",
    "bakery": "Piekarnia",
    "coffee_shop": "Kawiarnia",
    "ice_cream_shop": "Lodziarnia",
    "fast_food_restaurant": "Fast Food",
    "pizza_restaurant": "Pizzeria",
    "pub": "Pub",
    "steak_house": "Steakhouse",
    "sushi_restaurant": "Restauracja Sushi",
    "barbecue_restaurant": "Restauracja BBQ",
    "hamburger_restaurant": "Burgerownia",
    "italian_restaurant": "Restauracja włoska",
    "japanese_restaurant": "Restauracja japońska",
    "chinese_restaurant": "Restauracja chińska",
    "indian_restaurant": "Restauracja indyjska",
    "mexican_restaurant": "Restauracja meksykańska",
    "thai_restaurant": "Restauracja tajska",
    "vietnamese_restaurant": "Restauracja wietnamska",
    "french_restaurant": "Restauracja francuska",
    "greek_restaurant": "Restauracja grecka",
    "spanish_restaurant": "Restauracja hiszpańska",
    "korean_restaurant": "Restauracja koreańska",
    "turkish_restaurant": "Restauracja turecka",
    "american_restaurant": "Restauracja amerykańska",
    "vegan_restaurant": "Restauracja wegańska",
    "vegetarian_restaurant": "Restauracja wegetariańska",
    "fine_dining_restaurant": "Wykwintna restauracja",
    "brunch_restaurant": "Restauracja śniadaniowa",
    "breakfast_restaurant": "Restauracja śniadaniowa",
    "wine_bar": "Winiarnia",
    "donut_shop": "Pączkarnia",
    
    # --- Zakupy ---
    "shopping_mall": "Centrum handlowe",
    "clothing_store": "Sklep odzieżowy",
    "department_store": "Dom towarowy",
    "electronics_store": "Sklep z elektroniką",
    "gift_shop": "Sklep z pamiątkami",
    "grocery_store": "Sklep spożywczy",
    "supermarket": "Supermarket",
    "market": "Targ / Rynek",
    "book_store": "Księgarnia",
    "shoe_store": "Sklep obuwniczy",
    "sporting_goods_store": "Sklep sportowy",
    "jewelry_store": "Jubiler",
    "convenience_store": "Sklep całodobowy",
    "liquor_store": "Sklep monopolowy",
    "flower_store": "Kwiaciarnia",
    "florist": "Kwiaciarnia",
    "outlet_store": "Outlet",
    "store": "Sklep",

    # --- Natura i Sport ---
    "beach": "Plaża",
    "natural_feature": "Atrakcja przyrodnicza",
    "hiking_area": "Teren wspinaczkowy/wędrówkowy",
    "gym": "Siłownia",
    "fitness_center": "Centrum fitness",
    "stadium": "Stadion",
    "swimming_pool": "Basen",
    "sports_complex": "Kompleks sportowy",
    "athletic_field": "Boisko sportowe",
    "ski_resort": "Ośrodek narciarski",
    "golf_course": "Pole golfowe",
    "playground": "Plac zabaw",
    
    # --- Religia ---
    "church": "Kościół",
    "cathedral": "Katedra",
    "synagogue": "Synagoga",
    "mosque": "Meczet",
    "hindu_temple": "Świątynia hinduistyczna",
    "place_of_worship": "Miejsce kultu",

    # --- Noclegi ---
    "lodging": "Nocleg",
    "hotel": "Hotel",
    "hostel": "Hostel",
    "guest_house": "Pensjonat",
    "bed_and_breakfast": "Pensjonat B&B",
    "campground": "Kemping",
    "resort_hotel": "Kurort",
    "rv_park": "Park kamperowy",
    "motel": "Motel",

    # --- Transport (Ważne dla turysty) ---
    "airport": "Lotnisko",
    "international_airport": "Lotnisko międzynarodowe",
    "train_station": "Dworzec kolejowy",
    "bus_station": "Dworzec autobusowy",
    "subway_station": "Stacja metra",
    "transit_station": "Węzeł przesiadkowy",
    "ferry_terminal": "Terminal promowy",
    "taxi_stand": "Postój taksówek",
    "parking": "Parking",
    "gas_station": "Stacja paliw",
    "electric_vehicle_charging_station": "Stacja ładowania EV",
    "car_rental": "Wypożyczalnia samochodów",

    # --- Urzędy i Zdrowie (Ważne w nagłych wypadkach) ---
    "embassy": "Ambasada",
    "city_hall": "Ratusz",
    "police": "Policja",
    "post_office": "Poczta",
    "hospital": "Szpital",
    "pharmacy": "Apteka",
    "doctor": "Lekarz",
    "dentist": "Dentysta",
    "bank": "Bank",
    "atm": "Bankomat",

    # --- Typy techniczne / Ignorowane / Zbyt szczegółowe usługi ---
    # Te typy ustawiamy na None, aby funkcja filtrująca je pomijała
    "point_of_interest": None,
    "establishment": None,
    "administrative_area_level_1": None,
    "administrative_area_level_2": None,
    "administrative_area_level_3": None,
    "locality": None,
    "sublocality": None,
    "political": None,
    "neighborhood": None,
    "postal_code": None,
    "route": None,
    "street_address": None,
    "premise": None,
    "geocode": None,
    "intersection": None,
    
    # Usługi nieturystyczne
    "plumber": None,
    "roofing_contractor": None,
    "electrician": None,
    "moving_company": None,
    "locksmith": None,
    "painter": None,
    "contractor": None,
    "lawyer": None,
    "accounting": None,
    "real_estate_agency": None,
    "insurance_agency": None,
    "funeral_home": None,
    "cemetery": None,
    "storage": None,
    "wholesaler": None,
    "car_repair": None,
    "car_dealer": None,
    "car_wash": None,
    "laundry": None,
    "primary_school": None,
    "secondary_school": None,
    "school": None, 
    "university": "Uniwersytet", 
}

# Mapowanie kodów pogodowych Open-Meteo (WMO Weather interpretation codes) na język polski.
# Źródło: https://open-meteo.com/en/docs

WEATHER_CODES_PL = {
    0: "Bezchmurnie",
    1: "Częściowo słonecznie",
    2: "Częściowo pochmurnie",
    3: "Pochmurnie",
    45: "Mgła",
    48: "Osadzanie mroźnej mgły",
    51: "Słaba mżawka",
    53: "Umiarkowana mżawka",
    55: "Gęsta mżawka",
    56: "Słaba mżawka (zamarzająca)",
    57: "Gęsta mżawka (zamarzająca)",
    61: "Lekki deszcz",
    63: "Umiarkowany deszcz",
    65: "Silny deszcz",
    66: "Słaby deszcz (zamarzający)",
    67: "Silny deszcz (zamarzający)",
    71: "Lekki śnieg",
    73: "Umiarkowany śnieg",
    75: "Silny śnieg",
    77: "Opady śniegu (ziarnisty)",
    80: "Przelotne opady deszczu",
    81: "Częste przelotne opady deszczu",
    82: "Gwałtowne przelotne opady deszczu",
    85: "Przelotne opady śniegu",
    86: "Silne przelotne opady śniegu",
    95: "Burza",
    96: "Burza z lekkim gradem",
    99: "Burza z silnym gradem",
}
# Bazowe koszty dzienne w PLN dla różnych stylów podróży
BASE_COSTS = {
    "Ekonomiczny": 262.74,
    "Standardowy": 588.93,
    "Komfortowy": 1176.85,
}

# Mapowanie kodów pogodowych -> klucze ikon SVG
WEATHERCODE_TO_KEY = {
    0: 'clear',
    1: 'partly-cloudy',
    2: 'partly-cloudy',
    3: 'cloudy',
    45: 'fog',
    48: 'fog',
    51: 'drizzle',
    53: 'drizzle',
    55: 'drizzle',
    56: 'drizzle',
    57: 'drizzle',
    61: 'rain',
    63: 'rain',
    65: 'rain',
    66: 'rain',
    67: 'rain',
    71: 'snow',
    73: 'snow',
    75: 'snow',
    77: 'snow',
    80: 'rain',
    81: 'rain',
    82: 'rain',
    85: 'snow',
    86: 'snow',
    95: 'thunder',
    96: 'thunder',
    99: 'thunder'
}

# Mapowanie icon_key -> emoji
ICON_TO_EMOJI = {
    'clear': '☀️',
    'partly-cloudy': '⛅',
    'cloudy': '☁️',
    'fog': '🌫️',
    'drizzle': '🌦️',
    'rain': '🌧️',
    'snow': '❄️',
    'thunder': '⛈️',
    'unknown': '🌤️'
}

# Tłumaczenia tagów klimatu podróży (używane w suggestions.html)
TAG_TRANSLATIONS = {
    "beach_sun": "Plaża i Słońce",
    "nature": "Natura i Przyroda",
    "city_break": "City Break",
    "history_culture": "Historia i Kultura",
    "mountains_trekking": "Góry i Trekking",
    "food": "Kulinaria",
    "adventure": "Przygoda",
    "relaxation": "Relaks",
    "nightlife": "Życie Nocne",
    "nightlife_parties": "Życie Nocne i Imprezy",
    "luxury": "Luksus",
    "budget": "Budżetowo",
    "family": "Dla Rodzin",
    "wintersports": "Sporty Zimowe",
    "water_sports": "Sporty Wodne",
    "romantic": "Romantycznie",
    "solo_travel": "Podróż Solo",
    "shopping": "Zakupy",
    "art_design": "Sztuka i Design",
    "festivals": "Festiwale",
    "wellness_spa": "Wellness & Spa",
    "hidden_gems": "Ukryte Perełki",
    "road_trip": "Road Trip"
}
