"""Add vacation_type to GeneratedPlan

Revision ID: 1a9b85a930f3
Revises: cf269c451234
Create Date: 2025-11-03 00:23:37.130350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a9b85a930f3'
down_revision = 'cf269c451234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vacation_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('weather_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('attractions_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_plans', schema=None) as batch_op:
        batch_op.drop_column('attractions_data')
        batch_op.drop_column('weather_data')
        batch_op.drop_column('vacation_type')

    # ### end Alembic commands ###
