"""Initial schema

Revision ID: 7328198b8781
Revises: 
Create Date: 2025-11-05 15:28:57.648807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7328198b8781'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('generated_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('travel_style', sa.String(length=50), nullable=False),
    sa.Column('vacation_type', sa.String(length=50), nullable=True),
    sa.Column('data_start', sa.Date(), nullable=True),
    sa.Column('data_end', sa.Date(), nullable=True),
    sa.Column('total_cost_pln', sa.Float(), nullable=True),
    sa.Column('total_cost_local_currency', sa.Float(), nullable=True),
    sa.Column('local_currency_code', sa.String(length=3), nullable=True),
    sa.Column('weather_data', sa.JSON(), nullable=True),
    sa.Column('attractions_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generated_plans')
    op.drop_table('users')
    # ### end Alembic commands ###
