"""add destinations table

Revision ID: b5cd823438c9
Revises: 873e1359ca92
Create Date: 2025-12-04 14:38:44.855970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5cd823438c9'
down_revision = '873e1359ca92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('cost_tier', sa.String(length=50), nullable=True),
    sa.Column('cost_multiplier', sa.Float(), nullable=True),
    sa.Column('image_keyword', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('destinations')
    # ### end Alembic commands ###
