"""Add data_start and data_end to GeneratedPlan

Revision ID: dced783427ae
Revises: cf269c451234
Create Date: 2025-11-04 22:02:55.034658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dced783427ae'
down_revision = 'cf269c451234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_start', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('data_end', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_plans', schema=None) as batch_op:
        batch_op.drop_column('data_end')
        batch_op.drop_column('data_start')

    # ### end Alembic commands ###
